package com.projectvibrantjourneys.init.world.features;

import java.util.List;

import com.projectvibrantjourneys.init.object.PVJBlocks;
import com.projectvibrantjourneys.init.world.placements.PVJPlacements;
import com.projectvibrantjourneys.init.world.placements.PVJTreePlacements;

import net.minecraft.data.worldgen.placement.TreePlacements;
import net.minecraft.util.random.SimpleWeightedRandomList;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.WeightedPlacedFeature;
import net.minecraft.world.level.levelgen.feature.configurations.RandomFeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.stateproviders.WeightedStateProvider;
import net.minecraftforge.registries.RegistryObject;

public class PVJVegetationFeatures {

	public static final RegistryObject<ConfiguredFeature<?, ?>> TREES_PALM = PVJConfiguredFeatures.register("trees_palm", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.PALM_TREE_CHECKED.getHolder().get(), 0.8F)), PVJTreePlacements.PALM_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> TREES_JUNIPER = PVJConfiguredFeatures.register("trees_juniper", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, (new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.PALM_TREE_CHECKED.getHolder().get(), 0.8F)), PVJTreePlacements.PALM_TREE_CHECKED.getHolder().get()))));
	public static final RegistryObject<ConfiguredFeature<?, ?>> PINE_MEADOWS_TREES = PVJConfiguredFeatures.register("pine_meadows_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.PINE_TREE_CHECKED.getHolder().get(), 0.5F), new WeightedPlacedFeature(TreePlacements.OAK_BEES_0002, 0.2F), new WeightedPlacedFeature(TreePlacements.OAK_BEES_0002, 0.1F)), PVJPlacements.SPRUCE_BUSH.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> AUTUMNAL_CONIFEROUS_TREES = PVJConfiguredFeatures.register("autumnal_coniferous_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.TAMARACK_TREE_CHECKED.getHolder().get(), 0.3F), new WeightedPlacedFeature(PVJTreePlacements.TAMARACK_TREE_BEES_CHECKED.getHolder().get(), 0.05F), new WeightedPlacedFeature(PVJTreePlacements.FIR_TREE_CHECKED.getHolder().get(), 0.55F)), TreePlacements.SPRUCE_CHECKED)));
	public static final RegistryObject<ConfiguredFeature<?, ?>> BOREAL_FOREST_TREES = PVJConfiguredFeatures.register("boreal_forest_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.FIR_TREE_CHECKED.getHolder().get(), 0.75F), new WeightedPlacedFeature(PVJTreePlacements.PINE_TREE_CHECKED.getHolder().get(), 0.2F)), PVJTreePlacements.FIR_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> DESERT_SHRUBLAND_TREES = PVJConfiguredFeatures.register("desert_shrubland_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.JOSHUA_TREE_CHECKED.getHolder().get(), 0.8F)), PVJTreePlacements.JOSHUA_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> OVERGROWN_SPIRES_TREES = PVJConfiguredFeatures.register("overgrown_spires_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(TreePlacements.FANCY_OAK_CHECKED, 0.05F), new WeightedPlacedFeature(TreePlacements.JUNGLE_BUSH, 0.35F), new WeightedPlacedFeature(TreePlacements.MEGA_JUNGLE_TREE_CHECKED, 0.3F), new WeightedPlacedFeature(TreePlacements.DARK_OAK_CHECKED, 0.05F), new WeightedPlacedFeature(TreePlacements.OAK_CHECKED, 0.15F), new WeightedPlacedFeature(TreePlacements.JUNGLE_TREE_CHECKED, 0.2F)), TreePlacements.JUNGLE_TREE_CHECKED)));
	public static final RegistryObject<ConfiguredFeature<?, ?>> REDWOOD_FOREST_TREES = PVJConfiguredFeatures.register("redwood_forest_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.BIG_REDWOOD_TREE_CHECKED.getHolder().get(), 0.75F), new WeightedPlacedFeature(PVJTreePlacements.SMALL_REDWOOD_TREE_BEES_CHECKED.getHolder().get(), 0.05F), new WeightedPlacedFeature(PVJTreePlacements.SMALL_REDWOOD_TREE_CHECKED.getHolder().get(), 0.2F)), PVJTreePlacements.SMALL_REDWOOD_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> ASPEN_GROVE_TREES = PVJConfiguredFeatures.register("aspen_grove_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.ASPEN_TREE_BEES_CHECKED.getHolder().get(), 0.1F), new WeightedPlacedFeature(PVJTreePlacements.ASPEN_TREE_CHECKED.getHolder().get(), 0.2F), new WeightedPlacedFeature(PVJTreePlacements.RED_MAPLE_TREE_CHECKED.getHolder().get(), 0.15F), new WeightedPlacedFeature(PVJTreePlacements.ORANGE_MAPLE_TREE_CHECKED.getHolder().get(), 0.15F), new WeightedPlacedFeature(PVJTreePlacements.PURPLE_MAPLE_TREE_CHECKED.getHolder().get(), 0.15F), new WeightedPlacedFeature(PVJTreePlacements.FANCY_RED_MAPLE_TREE_CHECKED.getHolder().get(), 0.05F), new WeightedPlacedFeature(PVJTreePlacements.FANCY_ORANGE_MAPLE_TREE_CHECKED.getHolder().get(), 0.05F), new WeightedPlacedFeature(PVJTreePlacements.FANCY_PURPLE_MAPLE_TREE_CHECKED.getHolder().get(), 0.05F), new WeightedPlacedFeature(TreePlacements.FANCY_OAK_BEES, 0.25F)), TreePlacements.FANCY_OAK_BEES_0002)));
	public static final RegistryObject<ConfiguredFeature<?, ?>> MANGROVE_MARSH_TREES = PVJConfiguredFeatures.register("mangrove_marsh_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.MANGROVE_TREE_CHECKED.getHolder().get(), 0.9F)), PVJTreePlacements.MANGROVE_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> BAOBAB_FIELDs_TREES = PVJConfiguredFeatures.register("baobab_fields_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.BAOBAB_TREE_CHECKED.getHolder().get(), 0.9F)), TreePlacements.ACACIA_CHECKED)));
	public static final RegistryObject<ConfiguredFeature<?, ?>> WILLOW_WETLANDS_TREES = PVJConfiguredFeatures.register("willow_wetlands_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.WILLOW_TREE_CHECKED.getHolder().get(), 0.8F)), PVJTreePlacements.WILLOW_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> CRIMSON_THICKET_TREES = PVJConfiguredFeatures.register("crimson_thicket_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.RED_MAPLE_TREE_CHECKED.getHolder().get(), 0.15F), new WeightedPlacedFeature(PVJTreePlacements.FANCY_RED_MAPLE_TREE_CHECKED.getHolder().get(), 0.05F), new WeightedPlacedFeature(PVJTreePlacements.PURPLE_MAPLE_TREE_CHECKED.getHolder().get(), 0.15F), new WeightedPlacedFeature(PVJTreePlacements.FANCY_PURPLE_MAPLE_TREE_CHECKED.getHolder().get(), 0.05F), new WeightedPlacedFeature(TreePlacements.SPRUCE_CHECKED, 0.3F), new WeightedPlacedFeature(TreePlacements.PINE_CHECKED, 0.1F)), TreePlacements.SPRUCE_CHECKED)));
	public static final RegistryObject<ConfiguredFeature<?, ?>> CRYSTAL_LAKES_TREES = PVJConfiguredFeatures.register("crystal_lakes_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.FIR_TREE_CHECKED.getHolder().get(), 0.75F), new WeightedPlacedFeature(PVJTreePlacements.PINE_TREE_CHECKED.getHolder().get(), 0.2F)), PVJTreePlacements.FIR_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> WINDSWEPT_CLIFFS_TREES = PVJConfiguredFeatures.register("windswept_cliffs_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(TreePlacements.OAK_CHECKED, 0.6F), new WeightedPlacedFeature(TreePlacements.OAK_BEES_0002, 0.05F)), TreePlacements.SPRUCE_CHECKED)));
	public static final RegistryObject<ConfiguredFeature<?, ?>> PRAIRIE_TREES = PVJConfiguredFeatures.register("prairie_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.COTTONWOOD_TREE_BEES_CHECKED.getHolder().get(), 0.4F), new WeightedPlacedFeature(PVJTreePlacements.COTTONWOOD_TREE_CHECKED.getHolder().get(), 0.55F)), PVJTreePlacements.COTTONWOOD_TREE_CHECKED.getHolder().get())));
	public static final RegistryObject<ConfiguredFeature<?, ?>> BLOSSOMING_FIELDS_TREES = PVJConfiguredFeatures.register("blossoming_fields_trees", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.WHITE_SAKURA_TREE_BEES_CHECKED.getHolder().get(), 0.5F), new WeightedPlacedFeature(PVJTreePlacements.PINK_SAKURA_TREE_BEES_CHECKED.getHolder().get(), 0.5F)), PVJTreePlacements.PINK_SAKURA_TREE_BEES_CHECKED.getHolder().get())));
	
	public static final RegistryObject<ConfiguredFeature<?, ?>> EXTRA_VEGETATION_LUSH_CAVES = PVJConfiguredFeatures.register("extra_vegetation_lush_caves", () -> new ConfiguredFeature<>(Feature.RANDOM_SELECTOR, new RandomFeatureConfiguration(List.of(new WeightedPlacedFeature(PVJTreePlacements.MANGROVE_TREE_CHECKED.getHolder().get(), 0.4F)), PVJTreePlacements.MANGROVE_TREE_CHECKED.getHolder().get())));

	public static final RegistryObject<ConfiguredFeature<?, ?>> DESERT_AGAVE = PVJConfiguredFeatures.register("desert_agave", () -> new ConfiguredFeature<>(Feature.FLOWER, PVJConfiguredFeatures.simpleRandomPatch(new WeightedStateProvider(SimpleWeightedRandomList.<BlockState>builder().add(PVJBlocks.desert_agave.get().defaultBlockState(), 2).add(PVJBlocks.blooming_desert_agave.get().defaultBlockState(), 1)))));
	
	public static void init() {};
}